// 일본어 단어 데이터 (일본어, 읽기, 한국어 뜻)
const VOCABULARY = {
  basic: [
    { ja: "こんにちは", reading: "こんにちは", ko: "안녕하세요" },
    { ja: "ありがとう", reading: "ありがとう", ko: "감사합니다" },
    { ja: "さようなら", reading: "さようなら", ko: "안녕히 가세요" },
    { ja: "はい", reading: "はい", ko: "네" },
    { ja: "いいえ", reading: "いいえ", ko: "아니요" },
    { ja: "おはよう", reading: "おはよう", ko: "좋은 아침" },
    { ja: "こんばんは", reading: "こんばんは", ko: "좋은 저녁" },
    { ja: "すみません", reading: "すみません", ko: "죄송합니다" },
    { ja: "水", reading: "みず", ko: "물" },
    { ja: "食べ物", reading: "たべもの", ko: "음식" },
    { ja: "本", reading: "ほん", ko: "책" },
    { ja: "人", reading: "ひと", ko: "사람" },
    { ja: "友達", reading: "ともだち", ko: "친구" },
    { ja: "家", reading: "いえ", ko: "집" },
    { ja: "学校", reading: "がっこう", ko: "학교" },
    { ja: "今日", reading: "きょう", ko: "오늘" },
    { ja: "明日", reading: "あした", ko: "내일" },
    { ja: "大きい", reading: "おおきい", ko: "큰" },
    { ja: "小さい", reading: "ちいさい", ko: "작은" },
    { ja: "好き", reading: "すき", ko: "좋아하는" },
    { ja: "おいしい", reading: "おいしい", ko: "맛있는" },
    { ja: "暑い", reading: "あつい", ko: "덥다" },
    { ja: "寒い", reading: "さむい", ko: "춥다" },
    { ja: "新しい", reading: "あたらしい", ko: "새로운" },
    { ja: "古い", reading: "ふるい", ko: "오래된" },
    { ja: "高い", reading: "たかい", ko: "높다/비싸다" },
    { ja: "安い", reading: "やすい", ko: "싸다" },
    { ja: "速い", reading: "はやい", ko: "빠르다" },
    { ja: "遅い", reading: "おそい", ko: "느리다" },
  ],
  numbers: [
    { ja: "一", reading: "いち", ko: "1" },
    { ja: "二", reading: "に", ko: "2" },
    { ja: "三", reading: "さん", ko: "3" },
    { ja: "四", reading: "よん/し", ko: "4" },
    { ja: "五", reading: "ご", ko: "5" },
    { ja: "六", reading: "ろく", ko: "6" },
    { ja: "七", reading: "なな/しち", ko: "7" },
    { ja: "八", reading: "はち", ko: "8" },
    { ja: "九", reading: "きゅう/く", ko: "9" },
    { ja: "十", reading: "じゅう", ko: "10" },
    { ja: "百", reading: "ひゃく", ko: "100" },
    { ja: "千", reading: "せん", ko: "1000" },
    { ja: "万", reading: "まん", ko: "10000" },
    { ja: "零", reading: "れい", ko: "0" },
    { ja: "二十", reading: "にじゅう", ko: "20" },
    { ja: "三十", reading: "さんじゅう", ko: "30" },
    { ja: "五十", reading: "ごじゅう", ko: "50" },
    { ja: "百円", reading: "ひゃくえん", ko: "100엔" },
    { ja: "千円", reading: "せんえん", ko: "1000엔" },
    { ja: "一つ", reading: "ひとつ", ko: "하나 (개수)" },
  ],
  time: [
    { ja: "今", reading: "いま", ko: "지금" },
    { ja: "時", reading: "じ", ko: "시 (시간)" },
    { ja: "分", reading: "ふん", ko: "분" },
    { ja: "朝", reading: "あさ", ko: "아침" },
    { ja: "昼", reading: "ひる", ko: "낮" },
    { ja: "夜", reading: "よる", ko: "밤" },
    { ja: "月曜日", reading: "げつようび", ko: "월요일" },
    { ja: "火曜日", reading: "かようび", ko: "화요일" },
    { ja: "水曜日", reading: "すいようび", ko: "수요일" },
    { ja: "木曜日", reading: "もくようび", ko: "목요일" },
    { ja: "金曜日", reading: "きんようび", ko: "금요일" },
    { ja: "土曜日", reading: "どようび", ko: "토요일" },
    { ja: "日曜日", reading: "にちようび", ko: "일요일" },
    { ja: "今年", reading: "ことし", ko: "올해" },
    { ja: "去年", reading: "きょねん", ko: "작년" },
    { ja: "来年", reading: "らいねん", ko: "내년" },
    { ja: "春", reading: "はる", ko: "봄" },
    { ja: "夏", reading: "なつ", ko: "여름" },
    { ja: "秋", reading: "あき", ko: "가을" },
    { ja: "冬", reading: "ふゆ", ko: "겨울" },
    { ja: "昨日", reading: "きのう", ko: "어제" },
    { ja: "毎日", reading: "まいにち", ko: "매일" },
    { ja: "毎週", reading: "まいしゅう", ko: "매주" },
    { ja: "今週", reading: "こんしゅう", ko: "이번 주" },
    { ja: "来週", reading: "らいしゅう", ko: "다음 주" },
  ],
  verbs: [
    { ja: "行く", reading: "いく", ko: "가다" },
    { ja: "来る", reading: "くる", ko: "오다" },
    { ja: "食べる", reading: "たべる", ko: "먹다" },
    { ja: "飲む", reading: "のむ", ko: "마시다" },
    { ja: "見る", reading: "みる", ko: "보다" },
    { ja: "聞く", reading: "きく", ko: "듣다" },
    { ja: "話す", reading: "はなす", ko: "말하다" },
    { ja: "読む", reading: "よむ", ko: "읽다" },
    { ja: "書く", reading: "かく", ko: "쓰다" },
    { ja: "買う", reading: "かう", ko: "사다" },
    { ja: "売る", reading: "うる", ko: "팔다" },
    { ja: "働く", reading: "はたらく", ko: "일하다" },
    { ja: "勉強する", reading: "べんきょうする", ko: "공부하다" },
    { ja: "寝る", reading: "ねる", ko: "자다" },
    { ja: "起きる", reading: "おきる", ko: "일어나다" },
    { ja: "泳ぐ", reading: "およぐ", ko: "수영하다" },
    { ja: "歩く", reading: "あるく", ko: "걷다" },
    { ja: "走る", reading: "はしる", ko: "달리다" },
    { ja: "待つ", reading: "まつ", ko: "기다리다" },
    { ja: "座る", reading: "すわる", ko: "앉다" },
    { ja: "立つ", reading: "たつ", ko: "서다" },
    { ja: "開ける", reading: "あける", ko: "열다" },
    { ja: "閉める", reading: "しめる", ko: "닫다" },
    { ja: "貸す", reading: "かす", ko: "빌려주다" },
    { ja: "借りる", reading: "かりる", ko: "빌리다" },
  ],
  adjectives: [
    { ja: "美しい", reading: "うつくしい", ko: "아름답다" },
    { ja: "楽しい", reading: "たのしい", ko: "재미있다" },
    { ja: "悲しい", reading: "かなしい", ko: "슬프다" },
    { ja: "嬉しい", reading: "うれしい", ko: "기쁘다" },
    { ja: "難しい", reading: "むずかしい", ko: "어렵다" },
    { ja: "易しい", reading: "やさしい", ko: "쉽다" },
    { ja: "静か", reading: "しずか", ko: "조용하다" },
    { ja: "賑やか", reading: "にぎやか", ko: "시끄럽다/활기찬" },
    { ja: "綺麗", reading: "きれい", ko: "예쁘다/깨끗하다" },
    { ja: "有名", reading: "ゆうめい", ko: "유명하다" },
    { ja: "便利", reading: "べんり", ko: "편리하다" },
    { ja: "元気", reading: "げんき", ko: "건강하다/활발하다" },
    { ja: "簡単", reading: "かんたん", ko: "간단하다" },
    { ja: "大切", reading: "たいせつ", ko: "소중하다" },
    { ja: "素敵", reading: "すてき", ko: "멋지다" },
    { ja: "親切", reading: "しんせつ", ko: "친절하다" },
    { ja: "熱い", reading: "あつい", ko: "뜨겁다" },
    { ja: "冷たい", reading: "つめたい", ko: "차갑다" },
    { ja: "甘い", reading: "あまい", ko: "달다" },
    { ja: "辛い", reading: "からい", ko: "맵다" },
    { ja: "濃い", reading: "こい", ko: "진하다" },
    { ja: "薄い", reading: "うすい", ko: "얇다/연하다" },
    { ja: "広い", reading: "ひろい", ko: "넓다" },
    { ja: "狭い", reading: "せまい", ko: "좁다" },
    { ja: "明るい", reading: "あかるい", ko: "밝다" },
  ],
};

// 단어 세트 가져오기
function getWordSet(key) {
  if (key === "all") {
    return [
      ...VOCABULARY.basic,
      ...VOCABULARY.numbers,
      ...VOCABULARY.time,
      ...VOCABULARY.verbs,
      ...VOCABULARY.adjectives,
    ];
  }
  return VOCABULARY[key] || VOCABULARY.basic;
}
